eureka:
  instance:
    hostname: https://192.168.1.37
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/

  server:
    eviction-interval-timer-in-ms: 1000
    

server:
  port: 8088

spring:
  application:
    name: GControl-api-gateway-service
  profiles:
    active: stag
  cloud:
    gateway:
      routes:
        - id: GControl-ticket-management-service
          uri: lb://GCONTROL-TICKET-MANAGEMENT-SERVICE
          predicates:
            - Path=/osticket/**
          filters:
            - name: AuthenticationPrefilter
              args:
                apiAuthorization: true

